# Generated by Django 3.2.5 on 2022-03-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_num',
            new_name='emp_code',
        ),
    ]
